name: Web PR Build Check and Approval

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nave-wata/webtools/web:latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm dependencies
        working-directory: ./web
        run: npm install

      - name: Test Dioxus application
        working-directory: ./web
        run: cargo test

      - name: Build Tailwind CSS
        working-directory: ./web
        run: npx tailwindcss -i ./input.css -o ./assets/tailwind.css --minify

      - name: Build Dioxus application
        id: build-dioxus
        working-directory: ./web
        run: |
          chmod +x ./bundle.sh
          ./bundle.sh
