[package]
name = "WebTools"
version = "0.1.0"
authors = ["dioxus"]
edition = "2021"

[features]
default = ["production"]
production = []
development = []

[dependencies]
dioxus = { version = "0.6.0", features = ["router", "fullstack"] }
itertools = "0.14.0"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.133"
serde-wasm-bindgen = "0.6.5"
url = "2.5.4"
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.45"
web-sys = { version = "0.3.72", features = ["Clipboard", "EventTarget", "Navigator", "Request", "RequestInit", "RequestMode", "Response", "Window"] }

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
