[package]
name = "WebTools"
version = "0.1.0"
authors = ["dioxus"]
edition = "2021"

[features]
default = ["production"]
production = []
development = []

[dependencies]
dioxus = { version = "0.6.0", features = ["router", "fullstack"] }
itertools = "0.14.0"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
